create table COMPOSITION(
	COM_ID INTEGER PRIMARY KEY,
	COM_NM CHAR(2) not null
	);

create table DESCRIPTION(
	DESC_ID INTEGER not null,
	COM_ID INTEGER not null,
	DESCRIPT TEXT not null,
	CONSTRAINT DESCRIPTION_FK FOREIGN KEY(COM_ID)
	REFERENCES COMPOSITION(COM_ID)
	PRIMARY KEY(DESC_ID, COM_ID)
	);
