create table COMPOSITION(
	COM_ID INTEGER PRIMARY KEY,
	COM_NM CHAR(10) not null
	);

create table DESCRIPTION(
	COM_ID INTEGER not null,
	DESC_ID INTEGER not null,
	DESCRIPT TEXT not null,
	CONSTRAINT DESCRIPTION_FK FOREIGN KEY(COM_ID)
	REFERENCES COMPOSITION(COM_ID)
	PRIMARY KEY(COM_ID, DESC_ID)
	);


create table NUMBER_CODE(
	CODE INTEGER not null,
	COM_NUMBER INTEGER not null,
	COM_ID INTEGER not null,
	CONSTRAINT NUMBER_CODE_FG FOREIGN KEY(COM_ID)
	REFERENCES COMPOSITION(COM_ID)
	PRIMARY KEY(CODE, COM_NUMBER)
);

create table USER(
	ID TEXT PRIMARY KEY,
	PWD TEXT not null
);

INSERT INTO USER (ID, PWD)
VALUES ('admin', '1111');

INSERT INTO COMPOSITION(COM_ID, COM_NM)
VALUES (1, 'PASS');
INSERT INTO DESCRIPTION(COM_ID, DESC_ID, DESCRIPT)
VALUES (1, 1, ''),
(1,2,''),
(1,3,''),
(1,4,''),
(1,5,''),
(1,6,''),
(1,7,''),
(1,8,''),
(1,9,''),
(1,10,'');